name: build
on:
  push:
  pull_request:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - run: cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=ON . -B build
    - run: make lint
      working-directory: build
    - run: make beautify && git diff --exit-code
      working-directory: build
    - run: make JamJarTests && ctest
      working-directory: build
    - run: make
      working-directory: build
